/**
 * Role-Based Access Control Configuration
 * Defines permissions for each role in the system
 */

const ROLES = {
<<<<<<< HEAD
  ADMIN: 'ADMIN',
  GENERAL_USER: 'GENERAL_USER',
  PROGRAM_LEAD: 'PROGRAM_LEAD',
  HEAD_OF_PROGRAMS: 'HEAD_OF_PROGRAMS',
  FINANCE_CLERK: 'FINANCE_CLERK',
  PROCUREMENT_OFFICER: 'PROCUREMENT_OFFICER',
  PROCUREMENT_COMMITTEE: 'PROCUREMENT_COMMITTEE'
=======
  GENERAL_USER: 'GENERAL_USER',
  PROGRAM_LEAD: 'PROGRAM_LEAD',
  HEAD_OF_PROGRAMS: 'HEAD_OF_PROGRAMS',
  FINANCE_CLERK: 'FINANCE_CLERK'
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
};

const PERMISSIONS = {
  // Request permissions
  CREATE_REQUEST: 'create_request',
  VIEW_OWN_REQUESTS: 'view_own_requests',
  VIEW_DEPARTMENT_REQUESTS: 'view_department_requests',
  VIEW_ALL_REQUESTS: 'view_all_requests',
  EDIT_REQUEST: 'edit_request',
  DELETE_REQUEST: 'delete_request',
  SUBMIT_REQUEST: 'submit_request',
  
  // Approval permissions
  APPROVE_AS_LEAD: 'approve_as_lead',
  APPROVE_AS_HOP: 'approve_as_hop',
  APPROVE_AS_FINANCE: 'approve_as_finance',
  REJECT_REQUEST: 'reject_request',
  
  // Budget permissions
  VIEW_BUDGET_LINES: 'view_budget_lines',
  MANAGE_BUDGET_LINES: 'manage_budget_lines',
  TOP_UP_BUDGET: 'top_up_budget',
  
  // Reports
  VIEW_REPORTS: 'view_reports',
  EXPORT_DATA: 'export_data',
  
  // User management
  VIEW_USERS: 'view_users',
<<<<<<< HEAD
  MANAGE_USERS: 'manage_users',

  // Procurement permissions
  CREATE_PURCHASE_REQUEST: 'create_purchase_request',
  VIEW_PURCHASE_REQUESTS: 'view_purchase_requests',
  APPROVE_PURCHASE_REQUEST: 'approve_purchase_request',
  MANAGE_QUOTATIONS: 'manage_quotations',
  MANAGE_VENDORS: 'manage_vendors',
  COMMITTEE_REVIEW: 'committee_review',
  PROC_FINANCE_APPROVE: 'proc_finance_approve'
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    // Full system access - all permissions
    PERMISSIONS.CREATE_REQUEST,
    PERMISSIONS.VIEW_OWN_REQUESTS,
    PERMISSIONS.VIEW_DEPARTMENT_REQUESTS,
    PERMISSIONS.VIEW_ALL_REQUESTS,
    PERMISSIONS.EDIT_REQUEST,
    PERMISSIONS.DELETE_REQUEST,
    PERMISSIONS.SUBMIT_REQUEST,
    PERMISSIONS.APPROVE_AS_LEAD,
    PERMISSIONS.APPROVE_AS_HOP,
    PERMISSIONS.APPROVE_AS_FINANCE,
    PERMISSIONS.REJECT_REQUEST,
    PERMISSIONS.VIEW_BUDGET_LINES,
    PERMISSIONS.MANAGE_BUDGET_LINES,
    PERMISSIONS.TOP_UP_BUDGET,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.CREATE_PURCHASE_REQUEST,
    PERMISSIONS.VIEW_PURCHASE_REQUESTS,
    PERMISSIONS.APPROVE_PURCHASE_REQUEST,
    PERMISSIONS.MANAGE_QUOTATIONS,
    PERMISSIONS.MANAGE_VENDORS,
    PERMISSIONS.COMMITTEE_REVIEW,
    PERMISSIONS.PROC_FINANCE_APPROVE
  ],
  
=======
  MANAGE_USERS: 'manage_users'
};

const ROLE_PERMISSIONS = {
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
  [ROLES.GENERAL_USER]: [
    PERMISSIONS.CREATE_REQUEST,
    PERMISSIONS.VIEW_OWN_REQUESTS,
    PERMISSIONS.EDIT_REQUEST,
    PERMISSIONS.DELETE_REQUEST,
    PERMISSIONS.SUBMIT_REQUEST,
<<<<<<< HEAD
    PERMISSIONS.VIEW_BUDGET_LINES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.CREATE_PURCHASE_REQUEST,
    PERMISSIONS.VIEW_PURCHASE_REQUESTS
=======
    PERMISSIONS.VIEW_BUDGET_LINES
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
  ],
  
  [ROLES.PROGRAM_LEAD]: [
    PERMISSIONS.VIEW_OWN_REQUESTS,
    PERMISSIONS.VIEW_DEPARTMENT_REQUESTS,
    PERMISSIONS.APPROVE_AS_LEAD,
    PERMISSIONS.REJECT_REQUEST,
    PERMISSIONS.VIEW_BUDGET_LINES,
<<<<<<< HEAD
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.CREATE_PURCHASE_REQUEST,
    PERMISSIONS.VIEW_PURCHASE_REQUESTS,
    PERMISSIONS.APPROVE_PURCHASE_REQUEST
=======
    PERMISSIONS.VIEW_REPORTS
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
  ],
  
  [ROLES.HEAD_OF_PROGRAMS]: [
    PERMISSIONS.VIEW_OWN_REQUESTS,
<<<<<<< HEAD
    PERMISSIONS.VIEW_DEPARTMENT_REQUESTS,
    PERMISSIONS.APPROVE_AS_HOP,
    PERMISSIONS.REJECT_REQUEST,
    PERMISSIONS.VIEW_BUDGET_LINES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.CREATE_PURCHASE_REQUEST,
    PERMISSIONS.VIEW_PURCHASE_REQUESTS,
    PERMISSIONS.APPROVE_PURCHASE_REQUEST
  ],
  
  [ROLES.FINANCE_CLERK]: [
    // Finance clerks can also act as requesters (Float & Procurement)
    PERMISSIONS.CREATE_REQUEST,
    PERMISSIONS.VIEW_OWN_REQUESTS,
    PERMISSIONS.EDIT_REQUEST,
    PERMISSIONS.DELETE_REQUEST,
    PERMISSIONS.SUBMIT_REQUEST,
    // Approver capabilities
=======
    PERMISSIONS.VIEW_ALL_REQUESTS,
    PERMISSIONS.APPROVE_AS_HOP,
    PERMISSIONS.REJECT_REQUEST,
    PERMISSIONS.VIEW_BUDGET_LINES,
    PERMISSIONS.VIEW_REPORTS
    // Note: EXPORT_DATA removed - only Finance can access Dispatch Desk
  ],
  
  [ROLES.FINANCE_CLERK]: [
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
    PERMISSIONS.VIEW_ALL_REQUESTS,
    PERMISSIONS.APPROVE_AS_FINANCE,
    PERMISSIONS.REJECT_REQUEST,
    PERMISSIONS.VIEW_BUDGET_LINES,
    PERMISSIONS.MANAGE_BUDGET_LINES,
    PERMISSIONS.TOP_UP_BUDGET,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_DATA,
<<<<<<< HEAD
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_PURCHASE_REQUEST,
    PERMISSIONS.VIEW_PURCHASE_REQUESTS,
    PERMISSIONS.APPROVE_PURCHASE_REQUEST,
    PERMISSIONS.PROC_FINANCE_APPROVE
  ],

  [ROLES.PROCUREMENT_OFFICER]: [
    PERMISSIONS.VIEW_PURCHASE_REQUESTS,
    PERMISSIONS.MANAGE_QUOTATIONS,
    PERMISSIONS.MANAGE_VENDORS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_BUDGET_LINES,
    PERMISSIONS.EXPORT_DATA
  ],

  [ROLES.PROCUREMENT_COMMITTEE]: [
    PERMISSIONS.VIEW_PURCHASE_REQUESTS,
    PERMISSIONS.COMMITTEE_REVIEW,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_BUDGET_LINES
=======
    PERMISSIONS.VIEW_USERS
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
  ]
};

// Request status workflow
<<<<<<< HEAD
// Updated: Admin requests follow Admin -> Lead/HOP -> Finance flow
const REQUEST_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_ADMIN_APPROVAL: 'PENDING_ADMIN_APPROVAL',
=======
const REQUEST_STATUS = {
  DRAFT: 'DRAFT',
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
  PENDING_LEAD_APPROVAL: 'PENDING_LEAD_APPROVAL',
  PENDING_HOP_APPROVAL: 'PENDING_HOP_APPROVAL',
  PENDING_FINANCE_APPROVAL: 'PENDING_FINANCE_APPROVAL',
  APPROVED: 'APPROVED',
<<<<<<< HEAD
  DISPATCHED: 'DISPATCHED',
  PENDING_RECONCILIATION: 'PENDING_RECONCILIATION',
  RECON_PENDING_LEAD: 'RECON_PENDING_LEAD',
  RECON_PENDING_FINANCE: 'RECON_PENDING_FINANCE',
  RECONCILED: 'RECONCILED',
=======
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

// Valid status transitions
<<<<<<< HEAD
// Admin requests: DRAFT -> PENDING_ADMIN_APPROVAL -> PENDING_FINANCE_APPROVAL
// (Admin OR HR Lead/HOP approves the single PENDING_ADMIN_APPROVAL stage)
const STATUS_TRANSITIONS = {
  [REQUEST_STATUS.DRAFT]: [REQUEST_STATUS.PENDING_LEAD_APPROVAL, REQUEST_STATUS.PENDING_ADMIN_APPROVAL, REQUEST_STATUS.CANCELLED],
  [REQUEST_STATUS.PENDING_ADMIN_APPROVAL]: [REQUEST_STATUS.PENDING_FINANCE_APPROVAL, REQUEST_STATUS.REJECTED],
  [REQUEST_STATUS.PENDING_LEAD_APPROVAL]: [REQUEST_STATUS.PENDING_FINANCE_APPROVAL, REQUEST_STATUS.REJECTED],
  [REQUEST_STATUS.PENDING_HOP_APPROVAL]: [REQUEST_STATUS.PENDING_FINANCE_APPROVAL, REQUEST_STATUS.REJECTED],
  [REQUEST_STATUS.PENDING_FINANCE_APPROVAL]: [REQUEST_STATUS.APPROVED, REQUEST_STATUS.REJECTED],
  [REQUEST_STATUS.APPROVED]: [REQUEST_STATUS.DISPATCHED],
  [REQUEST_STATUS.DISPATCHED]: [REQUEST_STATUS.PENDING_RECONCILIATION],
  [REQUEST_STATUS.PENDING_RECONCILIATION]: [REQUEST_STATUS.RECON_PENDING_LEAD, REQUEST_STATUS.DISPATCHED],
  [REQUEST_STATUS.RECON_PENDING_LEAD]: [REQUEST_STATUS.RECON_PENDING_FINANCE, REQUEST_STATUS.DISPATCHED],
  [REQUEST_STATUS.RECON_PENDING_FINANCE]: [REQUEST_STATUS.RECONCILED, REQUEST_STATUS.DISPATCHED],
  [REQUEST_STATUS.RECONCILED]: [],
=======
const STATUS_TRANSITIONS = {
  [REQUEST_STATUS.DRAFT]: [REQUEST_STATUS.PENDING_LEAD_APPROVAL, REQUEST_STATUS.CANCELLED],
  [REQUEST_STATUS.PENDING_LEAD_APPROVAL]: [REQUEST_STATUS.PENDING_HOP_APPROVAL, REQUEST_STATUS.REJECTED],
  [REQUEST_STATUS.PENDING_HOP_APPROVAL]: [REQUEST_STATUS.PENDING_FINANCE_APPROVAL, REQUEST_STATUS.REJECTED],
  [REQUEST_STATUS.PENDING_FINANCE_APPROVAL]: [REQUEST_STATUS.APPROVED, REQUEST_STATUS.REJECTED],
  [REQUEST_STATUS.APPROVED]: [],
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
  [REQUEST_STATUS.REJECTED]: [],
  [REQUEST_STATUS.CANCELLED]: []
};

<<<<<<< HEAD
// Finance department code — used for finance-manager access checks
const FINANCE_DEPT_CODE = 'FOS';

/**
 * Determine whether a user is a "Finance Manager":
 *   - ADMIN always qualifies
 *   - HEAD_OF_PROGRAMS or PROGRAM_LEAD who belong to the Finance (FOS) department
 * Finance Managers are the only users who may create/edit/delete
 * budget lines, donors, and projects, and see all departments' data.
 * HOPs/Leads from HSD, CPJS, AHR etc. are scoped to their own department.
 */
const isFinanceManager = (user) => {
  if (!user) return false;
  if (user.role === ROLES.ADMIN) return true;
  return [ROLES.HEAD_OF_PROGRAMS, ROLES.PROGRAM_LEAD].includes(user.role) &&
    user.department_code === FINANCE_DEPT_CODE;
};

=======
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
// Check if user has permission
const hasPermission = (role, permission) => {
  const permissions = ROLE_PERMISSIONS[role];
  return permissions && permissions.includes(permission);
};

// Check if status transition is valid
const isValidTransition = (currentStatus, newStatus) => {
  const validTransitions = STATUS_TRANSITIONS[currentStatus];
  return validTransitions && validTransitions.includes(newStatus);
};

<<<<<<< HEAD
// Get required role(s) for approval based on current status
const getRequiredApprovalRole = (currentStatus) => {
  switch (currentStatus) {
    case REQUEST_STATUS.PENDING_ADMIN_APPROVAL:
      return [ROLES.ADMIN, ROLES.PROGRAM_LEAD, ROLES.HEAD_OF_PROGRAMS];
    case REQUEST_STATUS.PENDING_LEAD_APPROVAL:
      return [ROLES.PROGRAM_LEAD, ROLES.HEAD_OF_PROGRAMS]; // Either can approve
    case REQUEST_STATUS.PENDING_HOP_APPROVAL:
      return [ROLES.HEAD_OF_PROGRAMS];
    case REQUEST_STATUS.PENDING_FINANCE_APPROVAL:
      return [ROLES.FINANCE_CLERK, ROLES.HEAD_OF_PROGRAMS, ROLES.PROGRAM_LEAD];
=======
// Get required role for approval based on current status
const getRequiredApprovalRole = (currentStatus) => {
  switch (currentStatus) {
    case REQUEST_STATUS.PENDING_LEAD_APPROVAL:
      return ROLES.PROGRAM_LEAD;
    case REQUEST_STATUS.PENDING_HOP_APPROVAL:
      return ROLES.HEAD_OF_PROGRAMS;
    case REQUEST_STATUS.PENDING_FINANCE_APPROVAL:
      return ROLES.FINANCE_CLERK;
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
    default:
      return null;
  }
};

// Get next status after approval
const getNextApprovalStatus = (currentStatus) => {
  switch (currentStatus) {
    case REQUEST_STATUS.DRAFT:
      return REQUEST_STATUS.PENDING_LEAD_APPROVAL;
<<<<<<< HEAD
    case REQUEST_STATUS.PENDING_ADMIN_APPROVAL:
      return REQUEST_STATUS.PENDING_FINANCE_APPROVAL;
    case REQUEST_STATUS.PENDING_LEAD_APPROVAL:
      return REQUEST_STATUS.PENDING_FINANCE_APPROVAL; // Skip HOP - goes directly to Finance
=======
    case REQUEST_STATUS.PENDING_LEAD_APPROVAL:
      return REQUEST_STATUS.PENDING_HOP_APPROVAL;
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
    case REQUEST_STATUS.PENDING_HOP_APPROVAL:
      return REQUEST_STATUS.PENDING_FINANCE_APPROVAL;
    case REQUEST_STATUS.PENDING_FINANCE_APPROVAL:
      return REQUEST_STATUS.APPROVED;
    default:
      return null;
  }
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  REQUEST_STATUS,
  STATUS_TRANSITIONS,
<<<<<<< HEAD
  FINANCE_DEPT_CODE,
  hasPermission,
  isFinanceManager,
=======
  hasPermission,
>>>>>>> d4c8bc76b49626037845f6abf644ee02f76d0b87
  isValidTransition,
  getRequiredApprovalRole,
  getNextApprovalStatus
};
